### PR TITLE
Portfolio: accessibility

### PR DESCRIPTION
**Pull request by dagmawiii03**
**General requirements**

- Make sure that there are no _linter errors_
- Make sure that you used correct _GitHub flow_
- Make sure that you _documented your work_

**For this paritculat milestone, I created a separate pull request to check the accessablilty of your page, by checking the following points**

- Page titles ✔️ 
- Image text alternatives ✔️ 
- Text headings ✔️ 
- color contrast ✔️ 
- Resize ✔️
- Interaction ✔️
- Moving content ✔️
- Multimedia ✔️
- Basic structure of the page ✔️

### CODE REVIEW

**Review by franclobo — CHANGES_REQUESTED** [review]
Hi @dagmawiii03, 

# ♻️ Required Changes ♻️

so-close-jim-halpert

Good job so far!
You are doing it well 👏🏽 There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Page titles ✔️
- Image text alternatives ✔️
- Text headings ✔️
- Basic structure of the page ✔️


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [x] Please 🙏🏽 make sure to list all the requirements for building accessible websites, there are nine 👇🏽 

image

- [x] Kindly correct the buttons in contrast to having a 100% approved for an accessible web page. You can use [this aditus tool](https://www.aditus.io/button-contrast-checker/) to help to check the color contrast of the project. 👇🏽 

image




Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by dagmawiii03** [comment]
Hi 👋🏿  @franclobo....Thanks for the feedback

- The reason I haven't added the all the list requirements is that because my website don't got any moving or multimedia content
- and on the color contrast side, I did use the actual color code on the figma template, do you mean that, I need to change it to other smililar colors by trial and error method and check back with [his aditus tool](https://www.aditus.io/button-contrast-checker/) until I get 100% result?

**Comment by dagmawiii03** [comment]
Corrected the buttons constrant with 100% AAA standard, and cheked using [this aditus tool](https://www.aditus.io/button-contrast-checker/) and have achieved a result given [here](https://www.aditus.io/button-contrast-checker/dagmawiii03-github-io-2023-03-01-at-12-07-00-173?overview)

Screenshot from 2023-03-01 15-12-31

**Review by TadesseDev — APPROVED** [review]
### Hi @dagmawiii03 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
giphy (1)

## Highlights
 - [x] Good job making the changes requested by the previous code reviewer. ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
